export const teamDefault = {
    memberArray: [],
    teamDetail:[],
    teamChatMessageArray:[],
    teamChatPagination:null,
    individualLeaderBoard: {
        "overall": [],
        "year": [],
        "month": [],
        "week": [],
        "currentStreak": [],
        "bestStreak": [],
        "america": [],
        "europe": [],
        "asia": [],
        "pacific": [],
    },
    teamLeaderBoard: {
        "overall": [],
        "year": [],
        "month": [],
        "week": [],
    },
    teamAchievementDetail: {},
    teamAchievements:[],
    teamAchievementsPagination:null,
    teamChatDisplayList: [],
    teamMemberEventPagination: null,
    teamMemberEventList: [],
    memberDetail:null,
    seenActivity: [],
    userEventList: [],
    userEventPagination: null,
    teamGlobalStatistic: {},
    seenUserEvents: [],
    eventBadgeCount: 0,
    startEventViews: null
};